/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasimenu;

import java.awt.Font;

/**
 *
 * @author user
 */
public class BiodataOrganisasi extends javax.swing.JFrame {

    /**
     * Creates new form BiodataOrganisasi
     */
    public BiodataOrganisasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        namaTA = new javax.swing.JLabel();
        namaTF = new javax.swing.JTextField();
        pekerjaanTA = new javax.swing.JLabel();
        pekerjaanCB = new javax.swing.JComboBox<>();
        alamatTA = new javax.swing.JLabel();
        alamatTF = new javax.swing.JTextField();
        jkTA = new javax.swing.JLabel();
        menRB = new javax.swing.JRadioButton();
        womenRB = new javax.swing.JRadioButton();
        boldCB = new javax.swing.JCheckBox();
        miringCB = new javax.swing.JCheckBox();
        hasilTA = new javax.swing.JTextField();
        showBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Biodata"));

        namaTA.setForeground(new java.awt.Color(255, 255, 255));
        namaTA.setText("Nama");

        pekerjaanTA.setForeground(new java.awt.Color(255, 255, 255));
        pekerjaanTA.setText("Pekerjaan");

        pekerjaanCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Karyawan Swasta", "Pengusaha", "Pegawai Negeri Sipil", "Wiraswasta", "Ibu Rumah Tangga", "Lainnya" }));
        pekerjaanCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaanCBActionPerformed(evt);
            }
        });

        alamatTA.setForeground(new java.awt.Color(255, 255, 255));
        alamatTA.setText("Alamat");

        alamatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatTFActionPerformed(evt);
            }
        });

        jkTA.setForeground(new java.awt.Color(255, 255, 255));
        jkTA.setText("Jenis Kelamin");

        menRB.setBackground(new java.awt.Color(51, 51, 51));
        jkButtonGroup.add(menRB);
        menRB.setForeground(new java.awt.Color(255, 255, 255));
        menRB.setText("Laki-laki");
        menRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRBActionPerformed(evt);
            }
        });

        womenRB.setBackground(new java.awt.Color(51, 51, 51));
        jkButtonGroup.add(womenRB);
        womenRB.setForeground(new java.awt.Color(255, 255, 255));
        womenRB.setText("Perempuan");

        boldCB.setBackground(new java.awt.Color(51, 51, 51));
        boldCB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boldCB.setForeground(new java.awt.Color(255, 255, 255));
        boldCB.setText("Cetak Tebal");
        boldCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                boldCBStateChanged(evt);
            }
        });

        miringCB.setBackground(new java.awt.Color(51, 51, 51));
        miringCB.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        miringCB.setForeground(new java.awt.Color(255, 255, 255));
        miringCB.setText("Cetak Miring");
        miringCB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                miringCBStateChanged(evt);
            }
        });

        hasilTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTAActionPerformed(evt);
            }
        });

        showBtn.setBackground(new java.awt.Color(51, 255, 0));
        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(0, 204, 255));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(255, 0, 0));
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boldCB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menRB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(womenRB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(miringCB)))
                    .addComponent(alamatTA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pekerjaanCB, javax.swing.GroupLayout.Alignment.TRAILING, 0, 346, Short.MAX_VALUE)
                        .addComponent(namaTF, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pekerjaanTA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaTA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jkTA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(showBtn)
                            .addGap(60, 60, 60)
                            .addComponent(clearBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closeBtn))
                        .addComponent(hasilTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pekerjaanTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pekerjaanCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alamatTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jkTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menRB)
                    .addComponent(womenRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boldCB)
                    .addComponent(miringCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilTA, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showBtn)
                    .addComponent(clearBtn)
                    .addComponent(closeBtn))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menRBActionPerformed

    private void hasilTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTAActionPerformed

    private void pekerjaanCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaanCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pekerjaanCBActionPerformed

    private void alamatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatTFActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        String nama = namaTF.getText();
        String alamat = alamatTF.getText();
        String jk = "";
        String pekerjaan = String.valueOf(pekerjaanCB.getSelectedItem());
        
        if (menRB.isSelected()) {
            jk = menRB.getText();
        } else if (womenRB.isSelected()) {
            jk = womenRB.getText();
        } 
        
        if (boldCB.isSelected()) {
            hasilTA.setText("Nama: "+nama+"\n Alamat: " + alamat + "\nPekerjaan: " + pekerjaan + "\nJenis Kelamin: " + jk);
        } else if (miringCB.isSelected()) {
            hasilTA.setText("Nama: " + nama + "\nAlamat: " + alamat + "\nPekerjaan: " + pekerjaan + "\nJenis Kelamin: " + jk);
        } else {
            hasilTA.setText("Nama: " + nama + "\nAlamat: " + alamat + "\nPekerjaan: " + pekerjaan + "\nJenis Kelamin: " + jk);
        }
    }//GEN-LAST:event_showBtnActionPerformed

    private void boldCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_boldCBStateChanged
        // TODO add your handling code here:
        Font tebal = new Font("Arial", Font.BOLD, 12);
        Font normal = new Font("Arial", Font.PLAIN, 12);
        
        if (boldCB.isSelected()) {
            hasilTA.setFont(tebal);
        } else {
            hasilTA.setFont(normal);
        }
    }//GEN-LAST:event_boldCBStateChanged

    private void miringCBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_miringCBStateChanged
        // TODO add your handling code here:
        Font miring = new Font("Arial", Font.ITALIC, 12);
        Font normal = new Font("Arial", Font.PLAIN, 12);
        
        if (boldCB.isSelected()) {
            hasilTA.setFont(miring);
        } else {
            hasilTA.setFont(normal);
        }
    }//GEN-LAST:event_miringCBStateChanged

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        hasilTA.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataOrganisasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatTA;
    private javax.swing.JTextField alamatTF;
    private javax.swing.JCheckBox boldCB;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeBtn;
    private javax.swing.JTextField hasilTA;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jkButtonGroup;
    private javax.swing.JLabel jkTA;
    private javax.swing.JRadioButton menRB;
    private javax.swing.JCheckBox miringCB;
    private javax.swing.JLabel namaTA;
    private javax.swing.JTextField namaTF;
    private javax.swing.JComboBox<String> pekerjaanCB;
    private javax.swing.JLabel pekerjaanTA;
    private javax.swing.JButton showBtn;
    private javax.swing.JRadioButton womenRB;
    // End of variables declaration//GEN-END:variables
}
